//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.19 at 07:43:12 PM CEST 
//


package com.mgr.rtdm.domain;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for EventType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="EventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1}HeaderType"/>
 *         &lt;element name="Body" type="{http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1}BodyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="WSDLEvent" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
        "header",
        "body"
})
public class EventType {

    @XmlElement(name = "Header", required = true)
    protected HeaderType header;
    @XmlElement(name = "Body", required = true)
    protected BodyType body;
    @XmlAttribute(required = true)
    protected java.lang.String name;

    /**
     * Gets the value of the header property.
     *
     * @return possible object is
     * {@link HeaderType }
     */
    public HeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value allowed object is
     *              {@link HeaderType }
     */
    public void setHeader(HeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     *
     * @return possible object is
     * {@link BodyType }
     */
    public BodyType getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value allowed object is
     *              {@link BodyType }
     */
    public void setBody(BodyType value) {
        this.body = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link java.lang.String }
     */
    public java.lang.String getName() {
        if (name == null) {
            return "WSDLEvent";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link java.lang.String }
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

}
