//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.19 at 07:43:12 PM CEST 
//


package com.mgr.rtdm.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HeaderResponseType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="HeaderResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CorrelationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompletionTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderResponseType", propOrder = {
        "correlationId",
        "startTime",
        "completionTime"
})
public class HeaderResponseType {

    @XmlElement(name = "CorrelationId")
    protected java.lang.String correlationId;
    @XmlElement(name = "StartTime", required = true)
    protected java.lang.String startTime;
    @XmlElement(name = "CompletionTime", required = true)
    protected java.lang.String completionTime;

    /**
     * Gets the value of the correlationId property.
     *
     * @return possible object is
     * {@link java.lang.String }
     */
    public java.lang.String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     *
     * @param value allowed object is
     *              {@link java.lang.String }
     */
    public void setCorrelationId(java.lang.String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the startTime property.
     *
     * @return possible object is
     * {@link java.lang.String }
     */
    public java.lang.String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     *
     * @param value allowed object is
     *              {@link java.lang.String }
     */
    public void setStartTime(java.lang.String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the completionTime property.
     *
     * @return possible object is
     * {@link java.lang.String }
     */
    public java.lang.String getCompletionTime() {
        return completionTime;
    }

    /**
     * Sets the value of the completionTime property.
     *
     * @param value allowed object is
     *              {@link java.lang.String }
     */
    public void setCompletionTime(java.lang.String value) {
        this.completionTime = value;
    }

}
