//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.19 at 07:43:12 PM CEST 
//


package com.mgr.rtdm.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for HeaderType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="HeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClientTimeZoneID" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderType", propOrder = {
        "identity",
        "clientTimeZoneID"
})
public class HeaderType {

    @XmlElement(name = "Identity")
    protected java.lang.String identity;
    @XmlElement(name = "ClientTimeZoneID", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected java.lang.String clientTimeZoneID;

    /**
     * Gets the value of the identity property.
     *
     * @return possible object is
     * {@link java.lang.String }
     */
    public java.lang.String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     *
     * @param value allowed object is
     *              {@link java.lang.String }
     */
    public void setIdentity(java.lang.String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the clientTimeZoneID property.
     *
     * @return possible object is
     * {@link java.lang.String }
     */
    public java.lang.String getClientTimeZoneID() {
        return clientTimeZoneID;
    }

    /**
     * Sets the value of the clientTimeZoneID property.
     *
     * @param value allowed object is
     *              {@link java.lang.String }
     */
    public void setClientTimeZoneID(java.lang.String value) {
        this.clientTimeZoneID = value;
    }

}
