//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.19 at 07:43:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sas.com/xml/schema/sas-svcs/rtdm-1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED) package com.mgr.rtdm.domain;
