package com.mgr.common.scenario.data;

// Generated Apr 22, 2015 2:03:31 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Klasa opisujaca tabele SCENARIO Scenario generated by hbm2java
 */
@Entity
@Table(name = "SCENARIO")
public class Scenario implements java.io.Serializable {

    private ScenarioId id;
    private String eventName;
    private String charName1;
    private String charVal1;
    private String charName2;
    private String charVal2;
    private String charName3;
    private String charVal3;
    private String charName4;
    private String charVal4;
    private String charName5;
    private String charVal5;
    private String intName1;
    private BigDecimal intVal1;
    private String intName2;
    private BigDecimal intVal2;
    private String intName3;
    private BigDecimal intVal3;
    private String intName4;
    private BigDecimal intVal4;
    private String intName5;
    private BigDecimal intVal5;
    private String floatName1;
    private BigDecimal floatVal1;
    private String floatName2;
    private BigDecimal floatVal2;
    private String floatName3;
    private BigDecimal floatVal3;
    private String floatName4;
    private BigDecimal floatVal4;
    private String floatName5;
    private BigDecimal floatVal5;
    private String dateName1;
    private Timestamp dateVal1;
    private String dateName2;
    private Timestamp dateVal2;
    private String dateName3;
    private Timestamp dateVal3;
    private String dateName4;
    private Timestamp dateVal4;
    private String dateName5;
    private Timestamp dateVal5;

    public Scenario() {
    }

    public Scenario(ScenarioId id, String eventName) {
        this.id = id;
        this.eventName = eventName;
    }

    public Scenario(ScenarioId id, String eventName, String charName1,
                    String charVal1, String charName2, String charVal2,
                    String charName3, String charVal3, String charName4,
                    String charVal4, String charName5, String charVal5,
                    String intName1, BigDecimal intVal1, String intName2,
                    BigDecimal intVal2, String intName3, BigDecimal intVal3,
                    String intName4, BigDecimal intVal4, String intName5,
                    BigDecimal intVal5, String floatName1, BigDecimal floatVal1,
                    String floatName2, BigDecimal floatVal2, String floatName3,
                    BigDecimal floatVal3, String floatName4, BigDecimal floatVal4,
                    String floatName5, BigDecimal floatVal5, String dateName1,
                    Timestamp dateVal1, String dateName2, Timestamp dateVal2,
                    String dateName3, Timestamp dateVal3, String dateName4,
                    Timestamp dateVal4, String dateName5, Timestamp dateVal5) {
        this.id = id;
        this.eventName = eventName;
        this.charName1 = charName1;
        this.charVal1 = charVal1;
        this.charName2 = charName2;
        this.charVal2 = charVal2;
        this.charName3 = charName3;
        this.charVal3 = charVal3;
        this.charName4 = charName4;
        this.charVal4 = charVal4;
        this.charName5 = charName5;
        this.charVal5 = charVal5;
        this.intName1 = intName1;
        this.intVal1 = intVal1;
        this.intName2 = intName2;
        this.intVal2 = intVal2;
        this.intName3 = intName3;
        this.intVal3 = intVal3;
        this.intName4 = intName4;
        this.intVal4 = intVal4;
        this.intName5 = intName5;
        this.intVal5 = intVal5;
        this.floatName1 = floatName1;
        this.floatVal1 = floatVal1;
        this.floatName2 = floatName2;
        this.floatVal2 = floatVal2;
        this.floatName3 = floatName3;
        this.floatVal3 = floatVal3;
        this.floatName4 = floatName4;
        this.floatVal4 = floatVal4;
        this.floatName5 = floatName5;
        this.floatVal5 = floatVal5;
        this.dateName1 = dateName1;
        this.dateVal1 = dateVal1;
        this.dateName2 = dateName2;
        this.dateVal2 = dateVal2;
        this.dateName3 = dateName3;
        this.dateVal3 = dateVal3;
        this.dateName4 = dateName4;
        this.dateVal4 = dateVal4;
        this.dateName5 = dateName5;
        this.dateVal5 = dateVal5;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "scenarioGroup", column = @Column(name = "SCENARIO_GROUP", nullable = false, length = 20)),
            @AttributeOverride(name = "scenarioSeqNum", column = @Column(name = "SCENARIO_SEQ_NUM", nullable = false, precision = 22, scale = 0))})
    public ScenarioId getId() {
        return this.id;
    }

    public void setId(ScenarioId id) {
        this.id = id;
    }

    @Column(name = "EVENT_NAME", nullable = false, length = 50)
    public String getEventName() {
        return this.eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    @Column(name = "CHAR_NAME_1", length = 50)
    public String getCharName1() {
        return this.charName1;
    }

    public void setCharName1(String charName1) {
        this.charName1 = charName1;
    }

    @Column(name = "CHAR_VAL_1", length = 200)
    public String getCharVal1() {
        return this.charVal1;
    }

    public void setCharVal1(String charVal1) {
        this.charVal1 = charVal1;
    }

    @Column(name = "CHAR_NAME_2", length = 50)
    public String getCharName2() {
        return this.charName2;
    }

    public void setCharName2(String charName2) {
        this.charName2 = charName2;
    }

    @Column(name = "CHAR_VAL_2", length = 200)
    public String getCharVal2() {
        return this.charVal2;
    }

    public void setCharVal2(String charVal2) {
        this.charVal2 = charVal2;
    }

    @Column(name = "CHAR_NAME_3", length = 50)
    public String getCharName3() {
        return this.charName3;
    }

    public void setCharName3(String charName3) {
        this.charName3 = charName3;
    }

    @Column(name = "CHAR_VAL_3", length = 200)
    public String getCharVal3() {
        return this.charVal3;
    }

    public void setCharVal3(String charVal3) {
        this.charVal3 = charVal3;
    }

    @Column(name = "CHAR_NAME_4", length = 50)
    public String getCharName4() {
        return this.charName4;
    }

    public void setCharName4(String charName4) {
        this.charName4 = charName4;
    }

    @Column(name = "CHAR_VAL_4", length = 200)
    public String getCharVal4() {
        return this.charVal4;
    }

    public void setCharVal4(String charVal4) {
        this.charVal4 = charVal4;
    }

    @Column(name = "CHAR_NAME_5", length = 50)
    public String getCharName5() {
        return this.charName5;
    }

    public void setCharName5(String charName5) {
        this.charName5 = charName5;
    }

    @Column(name = "CHAR_VAL_5", length = 200)
    public String getCharVal5() {
        return this.charVal5;
    }

    public void setCharVal5(String charVal5) {
        this.charVal5 = charVal5;
    }

    @Column(name = "INT_NAME_1", length = 50)
    public String getIntName1() {
        return this.intName1;
    }

    public void setIntName1(String intName1) {
        this.intName1 = intName1;
    }

    @Column(name = "INT_VAL_1", precision = 22, scale = 0)
    public BigDecimal getIntVal1() {
        return this.intVal1;
    }

    public void setIntVal1(BigDecimal intVal1) {
        this.intVal1 = intVal1;
    }

    @Column(name = "INT_NAME_2", length = 50)
    public String getIntName2() {
        return this.intName2;
    }

    public void setIntName2(String intName2) {
        this.intName2 = intName2;
    }

    @Column(name = "INT_VAL_2", precision = 22, scale = 0)
    public BigDecimal getIntVal2() {
        return this.intVal2;
    }

    public void setIntVal2(BigDecimal intVal2) {
        this.intVal2 = intVal2;
    }

    @Column(name = "INT_NAME_3", length = 50)
    public String getIntName3() {
        return this.intName3;
    }

    public void setIntName3(String intName3) {
        this.intName3 = intName3;
    }

    @Column(name = "INT_VAL_3", precision = 22, scale = 0)
    public BigDecimal getIntVal3() {
        return this.intVal3;
    }

    public void setIntVal3(BigDecimal intVal3) {
        this.intVal3 = intVal3;
    }

    @Column(name = "INT_NAME_4", length = 50)
    public String getIntName4() {
        return this.intName4;
    }

    public void setIntName4(String intName4) {
        this.intName4 = intName4;
    }

    @Column(name = "INT_VAL_4", precision = 22, scale = 0)
    public BigDecimal getIntVal4() {
        return this.intVal4;
    }

    public void setIntVal4(BigDecimal intVal4) {
        this.intVal4 = intVal4;
    }

    @Column(name = "INT_NAME_5", length = 50)
    public String getIntName5() {
        return this.intName5;
    }

    public void setIntName5(String intName5) {
        this.intName5 = intName5;
    }

    @Column(name = "INT_VAL_5", precision = 22, scale = 0)
    public BigDecimal getIntVal5() {
        return this.intVal5;
    }

    public void setIntVal5(BigDecimal intVal5) {
        this.intVal5 = intVal5;
    }

    @Column(name = "FLOAT_NAME_1", length = 50)
    public String getFloatName1() {
        return this.floatName1;
    }

    public void setFloatName1(String floatName1) {
        this.floatName1 = floatName1;
    }

    @Column(name = "FLOAT_VAL_1", precision = 22, scale = 5)
    public BigDecimal getFloatVal1() {
        return this.floatVal1;
    }

    public void setFloatVal1(BigDecimal floatVal1) {
        this.floatVal1 = floatVal1;
    }

    @Column(name = "FLOAT_NAME_2", length = 50)
    public String getFloatName2() {
        return this.floatName2;
    }

    public void setFloatName2(String floatName2) {
        this.floatName2 = floatName2;
    }

    @Column(name = "FLOAT_VAL_2", precision = 22, scale = 5)
    public BigDecimal getFloatVal2() {
        return this.floatVal2;
    }

    public void setFloatVal2(BigDecimal floatVal2) {
        this.floatVal2 = floatVal2;
    }

    @Column(name = "FLOAT_NAME_3", length = 50)
    public String getFloatName3() {
        return this.floatName3;
    }

    public void setFloatName3(String floatName3) {
        this.floatName3 = floatName3;
    }

    @Column(name = "FLOAT_VAL_3", precision = 22, scale = 5)
    public BigDecimal getFloatVal3() {
        return this.floatVal3;
    }

    public void setFloatVal3(BigDecimal floatVal3) {
        this.floatVal3 = floatVal3;
    }

    @Column(name = "FLOAT_NAME_4", length = 50)
    public String getFloatName4() {
        return this.floatName4;
    }

    public void setFloatName4(String floatName4) {
        this.floatName4 = floatName4;
    }

    @Column(name = "FLOAT_VAL_4", precision = 22, scale = 5)
    public BigDecimal getFloatVal4() {
        return this.floatVal4;
    }

    public void setFloatVal4(BigDecimal floatVal4) {
        this.floatVal4 = floatVal4;
    }

    @Column(name = "FLOAT_NAME_5", length = 50)
    public String getFloatName5() {
        return this.floatName5;
    }

    public void setFloatName5(String floatName5) {
        this.floatName5 = floatName5;
    }

    @Column(name = "FLOAT_VAL_5", precision = 22, scale = 5)
    public BigDecimal getFloatVal5() {
        return this.floatVal5;
    }

    public void setFloatVal5(BigDecimal floatVal5) {
        this.floatVal5 = floatVal5;
    }

    @Column(name = "DATE_NAME_1", length = 50)
    public String getDateName1() {
        return this.dateName1;
    }

    public void setDateName1(String dateName1) {
        this.dateName1 = dateName1;
    }

    @Column(name = "DATE_VAL_1")
    public Timestamp getDateVal1() {
        return this.dateVal1;
    }

    public void setDateVal1(Timestamp dateVal1) {
        this.dateVal1 = dateVal1;
    }

    @Column(name = "DATE_NAME_2", length = 50)
    public String getDateName2() {
        return this.dateName2;
    }

    public void setDateName2(String dateName2) {
        this.dateName2 = dateName2;
    }

    @Column(name = "DATE_VAL_2")
    public Timestamp getDateVal2() {
        return this.dateVal2;
    }

    public void setDateVal2(Timestamp dateVal2) {
        this.dateVal2 = dateVal2;
    }

    @Column(name = "DATE_NAME_3", length = 50)
    public String getDateName3() {
        return this.dateName3;
    }

    public void setDateName3(String dateName3) {
        this.dateName3 = dateName3;
    }

    @Column(name = "DATE_VAL_3")
    public Timestamp getDateVal3() {
        return this.dateVal3;
    }

    public void setDateVal3(Timestamp dateVal3) {
        this.dateVal3 = dateVal3;
    }

    @Column(name = "DATE_NAME_4", length = 50)
    public String getDateName4() {
        return this.dateName4;
    }

    public void setDateName4(String dateName4) {
        this.dateName4 = dateName4;
    }

    @Column(name = "DATE_VAL_4")
    public Timestamp getDateVal4() {
        return this.dateVal4;
    }

    public void setDateVal4(Timestamp dateVal4) {
        this.dateVal4 = dateVal4;
    }

    @Column(name = "DATE_NAME_5", length = 50)
    public String getDateName5() {
        return this.dateName5;
    }

    public void setDateName5(String dateName5) {
        this.dateName5 = dateName5;
    }

    @Column(name = "DATE_VAL_5")
    public Timestamp getDateVal5() {
        return this.dateVal5;
    }

    public void setDateVal5(Timestamp dateVal5) {
        this.dateVal5 = dateVal5;
    }

    @Override
    public String toString() {
        return getId() == null ? "" : getId().toString();
    }

}
