package com.mgr.common.scenario.data;

// Generated Apr 22, 2015 2:03:31 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.math.BigDecimal;

/**
 * Klasa opisujaca PK SCENARIO_ID ScenarioId generated by hbm2java
 */
@Embeddable
public class ScenarioId implements java.io.Serializable {

    private String scenarioGroup;
    private BigDecimal scenarioSeqNum;

    public ScenarioId() {
    }

    public ScenarioId(String scenarioGroup, BigDecimal scenarioSeqNum) {
        this.scenarioGroup = scenarioGroup;
        this.scenarioSeqNum = scenarioSeqNum;
    }

    @Column(name = "SCENARIO_GROUP", nullable = false, length = 20)
    public String getScenarioGroup() {
        return this.scenarioGroup;
    }

    public void setScenarioGroup(String scenarioGroup) {
        this.scenarioGroup = scenarioGroup;
    }

    @Column(name = "SCENARIO_SEQ_NUM", nullable = false, precision = 22, scale = 0)
    public BigDecimal getScenarioSeqNum() {
        return this.scenarioSeqNum;
    }

    public void setScenarioSeqNum(BigDecimal scenarioSeqNum) {
        this.scenarioSeqNum = scenarioSeqNum;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ScenarioId))
            return false;
        ScenarioId castOther = (ScenarioId) other;

        return ((this.getScenarioGroup() == castOther.getScenarioGroup()) || (this
                .getScenarioGroup() != null
                && castOther.getScenarioGroup() != null && this
                .getScenarioGroup().equals(castOther.getScenarioGroup())))
                && ((this.getScenarioSeqNum() == castOther.getScenarioSeqNum()) || (this
                .getScenarioSeqNum() != null
                && castOther.getScenarioSeqNum() != null && this
                .getScenarioSeqNum().equals(
                        castOther.getScenarioSeqNum())));
    }

    public int hashCode() {
        int result = 17;

        result = 37
                * result
                + (getScenarioGroup() == null ? 0 : this.getScenarioGroup()
                .hashCode());
        result = 37
                * result
                + (getScenarioSeqNum() == null ? 0 : this.getScenarioSeqNum()
                .hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "Scenario Group: " + getScenarioGroup() + " Scenario Seq: "
                + getScenarioSeqNum();
    }

}
